.TH "COLGREP" "1" "November 2013" "0.1" ""
.SH "NAME"
\fBcolgrep\fR \- a lightweigth colorizer for STDOUT pipe
.P
to always recognize what\'s important!
.SH SYNOPSIS
.P
\fBcolgrep\fR [\fB\-i\fR] <\fIpattern\fR> [\fIpattern\fR \.\.\.] [\fI\-c\fR \fIcolor\fR]
.br
\fBcolgrep\fR [\fIoptions\fR]
.SH DESCRIPTION
.P
TODO
.SH OPTIONS
.P
TODO
.SH EXAMPLES
.P
TODO
.SH AUTHOR
.P
\fBThomas Duerr\fR (thomduerr@gmail\.com)
.SH GITHUB
.P
http://github\.com/thomd/colgrep

