.TH "COLGREP" "1" "November 2014" "0.1" ""
.SH "NAME"
\fBcolgrep\fR \- colorize a stdin stream
.SH SYNOPSIS
.P
\fBcolgrep\fR [\fB\-h\fR] [\fB\-c\fR COLOR] [\fB\-b\fR] [\fB\-l\fR] [\fB\-i\fR] [\fB\-v\fR] <\fIPATTERN\fR> [\fIPATTERN\fR \.\.\.]  
.SH DESCRIPTION
.P
A lightweigth colorizer for a STDIN stream\. Like grep, but prints all lines\.
.SH OPTIONS
.P
\fB\-c\fR
    highlight color: blue, green (default), grey, red, yellow
.P
\fB\-b\fR
    colorize background
.P
\fB\-i\fR
    ignore case
.P
\fB\-v\fR
    invert match
.P
\fB\-l\fR
    colorize whole line
.SH EXAMPLES
.P
Highlight current calendar date in cal(1):
.P
.RS 2
.EX
  cal | colgrep $(date +%e) \-c red
.EE
.RE
.P
Highlight UDP request when using tcpdump(1):
.P
.RS 2
.EX
  tcpdump | colgrep UDP
.EE
.RE
.P
Highlight all HTTP redirects when requesting google\.de:
.P
.RS 2
.EX
  curl \-sIL google\.de | colgrep \-bi location
.EE
.RE
.P
Highlight all 404 requests in an apache access\.log:
.P
.RS 2
.EX
  tail \-f /var/log/apache/access\.log | colgrep " 404 " \-c red
.EE
.RE
.SH AUTHOR
.P
\fBThomas Duerr\fR (thomduerr@gmail\.com)
.SH GITHUB
.P
http://github\.com/thomd/colgrep

