#!/usr/bin/env python
import sys
import re
import argparse

colors = {'red': '\033[0;31m', 'green': '\033[0;32m', 'reset': '\033[0m'}

def colgrep(args):
	'''
	colorize pattern
	'''
	pattern = args.pattern[0]
	color = colors.get(args.color, colors.get('green'))
	pre = re.compile("(" + pattern + ")")
	for line in sys.stdin.readlines():
		out = pre.sub(color + "\g<1>" + colors.get('reset'), line)
		sys.stdout.write(out)

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('pattern', nargs='+', metavar='WORD', help='pattern to be colored')
	parser.add_argument('--color', '-c', help='highlight color')
	args = parser.parse_args()
	colgrep(args)

if __name__ == '__main__':
	main()
