#!/usr/bin/env python
import sys
import re
import argparse

colors = {'red': '\033[0;31m', 'green': '\033[0;32m', 'reset': '\033[0m'}

def colgrep(args):
	'''
	create a regular expression of all search pattern and replace every pattern
	surounded by ansi-color directives in every line.
	'''
	color = colors.get(args.color, colors.get('green'))
	exp = re.compile("(" + "|".join(args.pattern) + ")")
	for line in sys.stdin.readlines():
		out = exp.sub(color + "\g<1>" + colors.get('reset'), line)
		sys.stdout.write(out)

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('pattern', nargs='+', metavar='WORD', help='pattern to be colored')
	parser.add_argument('--color', '-c', help='highlight color')
	args = parser.parse_args()
	colgrep(args)

if __name__ == '__main__':
	main()
